export interface Fish {
  id: string;
  name: string;
  location: string;
  description: string;
  imagePath: string;
  bestTimeOfDay?: string;
  bestWeather?: string;
  baitType?: string;
}

export const fishes: Fish[] = [
  {
    id: "1",
    name: "Bluegill",
    location: "Most lakes and rivers",
    description: "A small yet common fish found in many bodies of water. Best caught in clear water near vegetation",
    imagePath: "/images/wildlife/fish/bluegill_location.png",
    bestTimeOfDay: "Early Morning or Late Evening",
    bestWeather: "Clear",
    baitType: "Bread, Cheese, Cricket",
  },
  {
    id: "2",
    name: "Bullhead Catfish",
    location: "Swamps and shallow waters around Lemoyne",
    description: "A bottom-dwelling fish commonly found in murky waters",
    imagePath: "/images/wildlife/fish/bullhead_catfish_location.png",
    bestTimeOfDay: "Night",
    bestWeather: "Overcast or Rainy",
    baitType: "Corn, Cheese",
  },
  {
    id: "3",
    name: "Chain Pickerel",
    location: "Kamassa River, Bayou Nwa",
    description: "Aggressive fish found in slow-moving waters. Known for their chain-like markings",
    imagePath: "/images/wildlife/fish/chain_pickerel_location.png",
    bestTimeOfDay: "Morning to Evening",
    bestWeather: "Any Weather",
    baitType: "River Lure, Live Worms",
  },
  {
    id: "4",
    name: "Channel Catfish",
    location: "Rivers and larger lakes in the south",
    description: "Large fish found in deep, muddy waters",
    imagePath: "/images/wildlife/fish/channel_catfish_location.png",
    bestTimeOfDay: "Night",
    bestWeather: "Overcast",
    baitType: "Corn, Cheese, River Lure",
  },
  {
    id: "5",
    name: "Lake Sturgeon",
    location: "Dakota River, Flat Iron Lake",
    description: "Large bottom-feeding fish that can grow to impressive sizes. Found in deep waters",
    imagePath: "/images/wildlife/fish/lake_sturgeon_location.png",
    bestTimeOfDay: "Early Morning",
    bestWeather: "Overcast",
    baitType: "Special Lake Lure, Special River Lure",
  },
  {
    id: "6",
    name: "Largemouth Bass",
    location: "Flat Iron Lake, San Luis River",
    description: "Aggressive predatory fish known for their size and fighting spirit",
    imagePath: "/images/wildlife/fish/largemouth_bass_location.png",
    bestTimeOfDay: "Dawn or Dusk",
    bestWeather: "Clear to Overcast",
    baitType: "Lake Lure, Special Spinner",
  },
  {
    id: "7",
    name: "Longnose Gar",
    location: "Swamps of Bayou Nwa",
    description: "A sharp-nosed predator that thrives in swampy waters",
    imagePath: "/images/wildlife/fish/longnose_gar_location.png",
    bestTimeOfDay: "Morning to Afternoon",
    bestWeather: "Warm and Clear",
    baitType: "Swamp Lure, Live Worms",
  },
  {
    id: "8",
    name: "Muskie",
    location: "Larger rivers and lakes in the north",
    description: "An aggressive predator with a reputation for challenging fights",
    imagePath: "/images/wildlife/fish/muskie_location.png",
    bestTimeOfDay: "Morning",
    bestWeather: "Overcast",
    baitType: "Lake Lure, Special River Lure",
  },
  {
    id: "9",
    name: "Northern Pike",
    location: "Lake Isabella, Dakota River",
    description: "Large predatory fish with sharp teeth. Known for their aggressive strikes",
    imagePath: "/images/wildlife/fish/northern_pike_location.png",
    bestTimeOfDay: "Early Morning",
    bestWeather: "Overcast",
    baitType: "River Lure, Special Spinner",
  },
  {
    id: "10",
    name: "Perch",
    location: "Rivers and lakes across the map",
    description: "A small and colorful fish found in calm waters",
    imagePath: "/images/wildlife/fish/perch_location.png",
    bestTimeOfDay: "Morning",
    bestWeather: "Clear",
    baitType: "Bread, Cheese, Worms",
  },
  {
    id: "11",
    name: "Redfin Pickerel",
    location: "Kamassa River, Lagras",
    description: "Small but aggressive fish often found in shallow waters near vegetation",
    imagePath: "/images/wildlife/fish/redfin_pickerel_location.png",
    bestTimeOfDay: "Any Time",
    bestWeather: "Any Weather",
    baitType: "Bread, Cheese, Cricket",
  },
  {
    id: "12",
    name: "Rock Bass",
    location: "Dakota River, Lake Owanjila",
    description: "Medium-sized fish that prefer rocky areas in rivers and lakes",
    imagePath: "/images/wildlife/fish/rock_bass_location.png",
    bestTimeOfDay: "Morning to Afternoon",
    bestWeather: "Clear",
    baitType: "River Lure, Crayfish",
  },
  {
    id: "13",
    name: "Smallmouth Bass",
    location: "Dakota River, Lake Owanjila",
    description: "Smaller than their largemouth cousins but known for their fighting spirit",
    imagePath: "/images/wildlife/fish/smallmouth_bass_location.png",
    bestTimeOfDay: "Dawn or Dusk",
    bestWeather: "Clear",
    baitType: "River Lure, Special Spinner",
  },
  {
    id: "14",
    name: "Sockeye Salmon",
    location: "Dakota River, Lake Isabella",
    description: "Migratory fish known for their red coloring during spawning season",
    imagePath: "/images/wildlife/fish/sockeye_salmon_location.png",
    bestTimeOfDay: "Morning",
    bestWeather: "Overcast",
    baitType: "River Lure, Special River Lure",
  },
  {
    id: "15",
    name: "Steelhead Trout",
    location: "Dakota River, Upper Montana River",
    description: "Prized game fish known for their strength and spectacular jumps when hooked",
    imagePath: "/images/wildlife/fish/steelhead_trout_location.png",
    bestTimeOfDay: "Early Morning",
    bestWeather: "Overcast or Rainy",
    baitType: "Special River Lure, Special Spinner",
  },
];
