export interface LegendaryCreature {
  id: string;
  name: string;
  nickname?: string;
  type: "Fish" | "Animal";
  location: string;
  description: string;
  imagePath: string;
  method: string;
}

export const legendaryCreatures: LegendaryCreature[] = [

  // ANIMALS
    {
    id: "LA1",
    name: "Legendary Beaver",
    nickname: "Malia",
    type: "Animal",
    location: "New Hanover",
    description: "A rare and elusive beaver known for its impressive size and unique coat",
    imagePath: "/images/wildlife/legendary/legendary_beaver.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA2",
    name: "Legendary Grizzly Bear",
    nickname: "Bharati",
    type: "Animal",
    location: "Grizzlies East",
    description: "A massive grizzly bear with battle scars from countless encounters. The terror of the Grizzlies",
    imagePath: "/images/wildlife/legendary/legendary_grizzly.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA3",
    name: "Legendary Bighorn Ram",
    type: "Animal",
    location: "Grizzlies West",
    description: "A majestic ram with a robust frame and massive curved horns",
    imagePath: "/images/wildlife/legendary/legendary_bighorn_ram.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA4",
    name: "Legendary Boar",
    nickname: "Oryx",
    type: "Animal",
    location: "Bluewater Marsh",
    description: "A colossal boar known for its aggressive nature and thick hide",
    imagePath: "/images/wildlife/legendary/legendary_boar.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA5",
    name: "Legendary Buck",
    nickname: "Obie",
    type: "Animal",
    location: "Big Valley",
    description: "A swift and elegant deer with impressive antlers",
    imagePath: "/images/wildlife/legendary/legendary_buck.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA6",
    name: "Legendary Coyote",
    nickname: "Suki",
    type: "Animal",
    location: "Scarlett Meadows",
    description: "A cunning and elusive predator, known for its sharp senses",
    imagePath: "/images/wildlife/legendary/legendary_coyote.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA7",
    name: "Legendary Elk",
    nickname: "Enyeto",
    type: "Animal",
    location: "Cumberland Forest",
    description: "A towering elk with a massive rack of antlers",
    imagePath: "/images/wildlife/legendary/legendary_elk.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA8",
    name: "Legendary Fox",
    nickname: "Layla",
    type: "Animal",
    location: "Scarlett Meadows",
    description: "A sly and swift predator with a distinct reddish coat",
    imagePath: "/images/wildlife/legendary/legendary_fox.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA9",
    name: "Legendary Moose",
    nickname: "Anoki",
    type: "Animal",
    location: "Roanoke Ridge",
    description: "A towering giant of the wilderness, this moose is an absolute unit of an animal",
    imagePath: "/images/wildlife/legendary/legendary_moose.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA10",
    name: "Legendary White Bison",
    type: "Animal",
    location: "Grizzlies West",
    description: "A ghostly white bison that roams the snowy plains of the Grizzlies",
    imagePath: "/images/wildlife/legendary/legendary_white_bison.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA11",
    name: "Legendary Wolf",
    nickname: "Hotah",
    type: "Animal",
    location: "Grizzlies East",
    description: "A fierce alpha wolf with sharp instincts and battle scars",
    imagePath: "/images/wildlife/legendary/legendary_wolf.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA12",
    name: "Legendary Giaguaro Panther",
    type: "Animal",
    location: "Scarlett Meadows",
    description: "A stealthy and deadly predator with a distinctive spotted coat",
    imagePath: "/images/wildlife/legendary/legendary_panther.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA13",
    name: "Legendary Bullgator",
    nickname: "Lacartus",
    type: "Animal",
    location: "Bayou Nwa",
    description: "A massive and ancient alligator, known for its ferocity and size",
    imagePath: "/images/wildlife/legendary/legendary_bullgator.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA14",
    name: "Legendary Cougar",
    type: "Animal",
    location: "Gaptooth Ridge",
    description: "A powerful and elusive predator, stalking prey across Gaptooth Ridge",
    imagePath: "/images/wildlife/legendary/legendary_cougar.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA15",
    name: "Legendary Pronghorn",
    nickname: "Ira",
    type: "Animal",
    location: "Rio Bravo",
    description: "A nimble and rare antelope with unique markings",
    imagePath: "/images/wildlife/legendary/legendary_pronghorn.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LA16",
    name: "Legendary Tatanka Bison",
    type: "Animal",
    location: "Hennigan's Stead",
    description: "A massive and imposing bison with dark fur and an impressive build",
    imagePath: "/images/wildlife/legendary/legendary_tatanka_bison.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },

  // FISH
  {
    id: "LF1",
    name: "Legendary Bluegill",
    type: "Fish",
    location: "Flat Iron Lake",
    description: "A brightly colored and rare bluegill that thrives in pristine waters",
    imagePath: "/images/wildlife/legendary/legendary_bluegill.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LF2",
    name: "Legendary Bullhead Catfish",
    type: "Fish",
    location: "Sisika Penitentiary",
    description: "A hefty and unique catfish with a distinctive whiskered face",
    imagePath: "/images/wildlife/legendary/legendary_bullhead_catfish.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //  {
    id: "LF3",
    name: "Legendary Chain Pickerel",
    type: "Fish",
    location: "Dakota River",
    description: "A long and slender pickerel known for its fierce strikes",
    imagePath: "/images/wildlife/legendary/legendary_chain_pickerel.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
    id: "LF4",
    name: "Legendary Lake Sturgeon",
    type: "Fish",
    location: "Flat Iron Lake",
    description: "A prehistoric giant of the waters with a rugged, scaly body",
    imagePath: "/images/wildlife/legendary/legendary_lake_sturgeon.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
  id: "LF5",
    name: "Legendary Largemouth Bass",
    type: "Fish",
    location: "San Louis River",
    description: "A robust and elusive bass known for its incredible size",
    imagePath: "/images/wildlife/legendary/legendary_largemouth_bass.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
  id: "LF6",
    name: "Legendary Longnose Gar",
    type: "Fish",
    location: "Flat Iron Lake",
    description: "A sharp-nosed predator fish with a fearsome reputation",
    imagePath: "/images/wildlife/legendary/legendary_longnose_gar.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
  id: "LF7",
    name: "Legendary Northern Pike",
    type: "Fish",
    location: "O'Creagh's Run",
    description: "A long and ferocious predator fish with a hunger for smaller prey",
    imagePath: "/images/wildlife/legendary/legendary_northern_pike.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
  id: "LF8",
    name: "Legendary Perch",
    type: "Fish",
    location: "Elysian Pool",
    description: "A vibrant and elusive perch that thrives in cool rivers",
    imagePath: "/images/wildlife/legendary/legendary_perch.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
  id: "LF9",
    name: "Legendary Redfin Pickerel",
    type: "Fish",
    location: "Stillwater Creek",
    description: "A bright and agile fish with a distinctive red fin",
    imagePath: "/images/wildlife/legendary/legendary_redfin_pickerel.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
  id: "LF10",
    name: "Legendary Rock Bass",
    type: "Fish",
    location: "Tall Trees",
    description: "A hefty and striking bass that lurks in rocky waters",
    imagePath: "/images/wildlife/legendary/legendary_rock_bass.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
{
  id: "LF11",
    name: "Legendary Smallmouth Bass",
    type: "Fish",
    location: "Big Valley",
    description: "A hardy bass known for its stamina and fierce fight",
    imagePath: "/images/wildlife/legendary/legendary_smallmouth_bass.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
  id: "LF12",
    name: "Legendary Sockeye Salmon",
    type: "Fish",
    location: "Grizzlies West",
    description: "A vibrant red salmon known for its leaps and power",
    imagePath: "/images/wildlife/legendary/legendary_sockeye_salmon.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },
  {
  id: "LF13",
    name: "Legendary Steelhead Trout",
    type: "Fish",
    location: "Roanoke Ridge",
    description: "A sleek and muscular trout that thrives in strong currents",
    imagePath: "/images/wildlife/legendary/legendary_steelhead_trout.png",
    method: "Legendary animals always give a clean pelt or skin, so any weapon can be used",
  },

];