export interface Wildlife {
  id: string;
  name: string;
  type: "Predator" | "Prey" | "Legendary";
  location: string;
  description: string;
  imagePath: string;
  hunting_method?: string;
  weapon_type?: string;
}

export const animals: Wildlife[] = [
  {
    id: "1",
    name: "Alligator",
    type: "Predator",
    location: "Bayou Nwa",
    description: "Massive and territorial predator. Extremely dangerous when provoked.",
    imagePath: "/images/wildlife/animals/alligator.png",
    hunting_method: "Long range, headshots preferred",
    weapon_type: "Rifle (High Velocity)",
  },
  {
    id: "2",
    name: "Armadillo",
    type: "Prey",
    location: "Cholla Springs, Gaptooth Ridge, Rio Bravo",
    description: "Armadillos are small mammals with a tough shell.",
    imagePath: "/images/wildlife/animals/armadillo.png",
    hunting_method: "Small game arrows",
    weapon_type: "Bow",
  },
  {
    id: "3",
    name: "Badger",
    type: "Prey",
    location: "Everywhere but the North",
    description:"Small and nocturnal, these burrowing mammals are known for their tenacity and striped faces",
    imagePath: "/images/wildlife/animals/badger.png",
    hunting_method: "",
    weapon_type:"Varmint Rifle",
  },
  {
    id: "4",
    name: "Bat",
    type: "Prey",
    location:"Aurora Basin, Bolger Glade, Elysian Pool",
    description:"Tiny flying mammals that navigate the night with echolocation",
    imagePath:"/images/wildlife/animals/bat.png",
    hunting_method:"Small game arrows",
    weapon_type:"Bow",
  },
  {
    id: "5",
    name: "Beaver",
    type: "Prey",
    location:"Owanjila, Lake Isabella, Huron Glen, Shady Belle",
    description:"Industrious rodents famous for building dams and lodges along rivers",
    imagePath:"/images/wildlife/animals/beaver.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  },
  {
    id: "6",
    name: "Bighorn",
    type: "Prey",
    location:"Mountain areas",
    description:"Majestic mountain sheep with large curved horns",
    imagePath:"/images/wildlife/animals/bighorn.png",
    hunting_method:"Poison Arrows",
    weapon_type:"Bow or Rifle",
  },
  {
    id: "7",
    name: "Bison",
    type: "Prey",
    location:"Great Plains, THe Heartlands, Emerald Ranch, Hennigan's Stead ",
    description:"Massive grazing animals that roam the plains in herds",
    imagePath:"/images/wildlife/animals/bison.png",
    hunting_method:"High powered weapons or Improved Arrows",
    weapon_type:"Carcano Rifle",
  },
  {
    id: "8",
    name: "Black Bear",
    type: "Predator",
    location:"Big Valley, Aurora Basin, Bayou Nwa, Roanoke Ridge",
    description:"Smaller than the grizzly but just as formidable in the wild",
    imagePath:"/images/wildlife/animals/blackbear.png",
    hunting_method:"Long scoped Rifle or Improved Arrows",
    weapon_type:"Rifle or Bow",
  },
  {
    id: "9",
    name: "Bluejay",
    type: "Prey",
    location:"Caliban's Seat, Roanoke Ridge",
    description:"Bright and noisy birds with striking blue plumage",
    imagePath:"/images/wildlife/animals/bluejay.png",
    hunting_method:"Small game arrows",
    weapon_type:"Bow",
  },
  {
    id: "10",
    name: "Boar",
    type: "Prey",
    location:"Lemoyne",
    description:"Wild and aggressive hogs often found in forests and swamps",
    imagePath:"/images/wildlife/animals/boar.png",
    hunting_method:"Poison Arrows",
    weapon_type:"Rifle or Bow",
  },
  {
    id: "11",
    name: "Booby",
    type: "Prey",
    location:"Guarma",
    description:"Tropical seabirds with bright feet, found near shorelines",
    imagePath:"/images/wildlife/animals/booby.png",
    hunting_method:"Small game arrows",
    weapon_type:"Bow",
  },
  {
    id: "12",
    name: "Buck",
    type: "Prey",
    location:"Everywhere except Grizzlies West",
    description:"Male deer with majestic antlers, symbolizing the wild",
    imagePath:"/images/wildlife/animals/buck.png",
    hunting_method:"Long range or Stealth",
    weapon_type:"Rifle or Bow",
  },
  {
    id: "13",
    name: "Bull",
    type: "Prey",
    location:"Carmody Dell, Hanging Dog Ranch, Hill Haven Ranch, Lakay",
    description:"Strong and sturdy male cattle, often used in farming",
    imagePath:"/images/wildlife/animals/bull.png",
    hunting_method:"Improved Arrows",
    weapon_type:"Bow",
  },
  {
    id: "14",
    name: "Bullfrog",
    type: "Prey",
    location:"Bayou Nwa",
    description:"Large amphibians with deep, croaking calls",
    imagePath:"/images/wildlife/animals/bullfrog.png",
    hunting_method:"Small game arrows",
    weapon_type:"Bow",
  },
  {
    id: "15",
    name: "Cardinal",
    type: "Prey",
    location:"Everywhere but New Austin",
    description:"Vivid red birds, a striking sight in the trees",
    imagePath:"/images/wildlife/animals/cardinal.png",
    hunting_method:"Small game arrows",
    weapon_type:"",
  },
  {
    id: "16",
    name: "Cat",
    type: "Prey",
    location:"Settlements and Homesteads",
    description:"Domesticated and independent, often found around settlements",
    imagePath:"/images/wildlife/animals/cat.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "17",
    name: "Chicken",
    type: "Prey",
    location:"Settlements",
    description:"Common farmyard fowl raised for eggs and meat",
    imagePath:"/images/wildlife/animals/chicken.png",
    hunting_method:"Small game Arrows",
    weapon_type:"",
  },
  {
    id: "18",
    name: "Chipmunk",
    type: "Prey",
    location:"Everywhere",
    description:"Tiny, striped rodents darting through the underbrush",
    imagePath:"/images/wildlife/animals/chipmunk.png",
    hunting_method:"Small game arrows",
    weapon_type:"",
  },
  {
    id: "19",
    name: "Condor",
    type: "Prey",
    location:"New Austin",
    description:"Giant scavenger birds soaring over deserts and canyons",
    imagePath:"/images/wildlife/animals/condor.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "20",
    name: "Cormorant",
    type: "Prey",
    location:"Shady Belle",
    description:"Aquatic birds known for their diving prowess",
    imagePath:"/images/wildlife/animals/cormorant.png",
    hunting_method:"",
    weapon_type:"Rifle or Bow",
  },
  {
    id: "21",
    name: "Cougar",
    type: "Predator",
    location:"New Austin, New Hanover, and West Elizabeth",
    description:"Stealthy and lethal predators stalking the wilderness",
    imagePath:"/images/wildlife/animals/cougar.png",
    hunting_method:"Enhanced or Poison Arrows",
    weapon_type:"",
  },
  {
    id: "22",
    name: "Cow",
    type: "Prey",
    location:"Select communities",
    description:"Docile grazing animals raised for milk and beef",
    imagePath:"/images/wildlife/animals/cow.png",
    hunting_method:"",
    weapon_type:"Long scope rifle",
  },
  {
    id: "23",
    name: "Coyote",
    type: "Predator",
    location:"Everywhere but Grizzlies West",
    description:"Wily canines adapted to a variety of environments",
    imagePath:"/images/wildlife/animals/coyote.png",
    hunting_method:"",
    weapon_type:"Rifle or Bow",
  },
  {
    id: "24",
    name: "Crane",
    type: "Prey",
    location:"Bayou Nwa",
    description:"Tall, elegant wading birds often seen near water",
    imagePath:"/images/wildlife/animals/crane.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  },
  {
    id: "25",
    name: "Crow",
    type: "Prey",
    location:"Everywhere",
    description:"Intelligent black birds that thrive almost everywhere",
    imagePath:"/images/wildlife/animals/crow.png",
    hunting_method:"Small game arrows",
    weapon_type:"",
  },
  {
    id: "26",
    name: "Crab",
    type: "Prey",
    location:"Guarma, Rio Bravo, Scarlett Meadows",
    description:"Hard-shelled crustaceans scuttling along beaches",
    imagePath:"/images/wildlife/animals/crab.png",
    hunting_method:"Small game arrows",
    weapon_type:"",
  },
  {
    id: "27",
    name: "Crayfish",
    type: "Prey",
    location:"Bayou Nwa",
    description:"Small freshwater crustaceans resembling tiny lobsters",
    imagePath:"/images/wildlife/animals/crayfish.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "28",
    name: "Deer",
    type: "Prey",
    location:"Everywhere except New Austin",
    description:"Graceful herbivores commonly found in forests and meadows",
    imagePath:"/images/wildlife/animals/deer.png",
    hunting_method:"Headshot",
    weapon_type:"Bow or Rifle",
  },
  {
    id: "29",
    name: "Dog",
    type: "Prey",
    location:"Settlements and nearby homesteads",
    description:"Loyal companions, found both as strays and pets",
    imagePath:"/images/wildlife/animals/dog.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "30",
    name: "Donkey",
    type: "Prey",
    location:"Horse Fence",
    description:"Sturdy pack animals often seen on farms and in towns",
    imagePath:"/images/wildlife/animals/donkey.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "31",
    name: "Duck",
    type: "Prey",
    location:"Everywhere except Grizzlies West and New Austin",
    description:"Waterfowl known for their distinctive quacks and webbed feet",
    imagePath:"/images/wildlife/animals/duck.png",
    hunting_method:"Small game arrows",
    weapon_type:"Bow",
  },
  {
    id: "32",
    name: "Eagle",
    type: "Prey",
    location:"Everywhere except Hennigan's Stead, Great Plains, or Bayou Nwa",
    description:"Majestic birds of prey with keen eyesight and sharp talons",
    imagePath:"/images/wildlife/animals/eagle.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "33",
    name: "Egret",
    type: "Prey",
    location:"Bayou Nwa",
    description:"Slender, white wading birds often seen in marshes",
    imagePath:"/images/wildlife/animals/egret.png",
    hunting_method:"Small game arrows",
    weapon_type:"",
  },
  {
    id: "34",
    name: "Elk",
    type: "Prey",
    location:"Southwest to the Northeast ",
    description:"Large deer with impressive antlers, roaming open fields",
    imagePath:"/images/wildlife/animals/elk.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "35",
    name: "Fox",
    type: "Predator",
    location:"Everywhere except Gaptooth Ridge",
    description:"Clever predators with bushy tails, adept at surviving in varied environments",
    imagePath:"/images/wildlife/animals/fox.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "36",
    name: "Gila Monster",
    type: "Predator",
    location:"Cholla Springs, Rio Bravo, and Gaptooth Ridge",
    description:"Venomous lizards with distinctive black-and-orange patterns",
    imagePath:"/images/wildlife/animals/gila_monster.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  },
  {
    id: "37",
    name: "Goat",
    type: "Prey",
    location:"Guarma",
    description:"Hardy, sure-footed animals often found on farms and rocky terrains",
    imagePath:"/images/wildlife/animals/goat.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "38",
    name: "Goose",
    type: "Prey",
    location:"Emerald Ranch",
    description:"Waterfowl with a loud honk, known for their migratory habits",
    imagePath:"/images/wildlife/animals/goose.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "39",
    name: "Grizzly",
    type: "Predator",
    location:"Aurora Basin, Little Creek River, Whinyard Strait, O'Creagh's Run",
    description:"Massive and powerful bears, true symbols of the wilderness",
    imagePath:"/images/wildlife/animals/grizzly.png",
    hunting_method:"",
    weapon_type:"High Velocity Rifle",
  },
  {
    id: "40",
    name: "Gull",
    type: "Prey",
    location: "Guarma, Saint Denis, Flat Iron Lake, Van Horn Trading Post",
    description:"Coastal birds scavenging along beaches and harbors",
    imagePath:"/images/wildlife/animals/gull.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "41",
    name: "Hawk",
    type: "Predator",
    location:"Everywhere",
    description:"Agile raptors known for their sharp vision and hunting prowess",
    imagePath:"/images/wildlife/animals/hawk.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "42",
    name: "Heron",
    type: "Prey",
    location:"Bayou Nwa",
    description:"Graceful wading birds with long legs and necks",
    imagePath:"/images/wildlife/animals/heron.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "43",
    name: "Iguana",
    type: "Prey",
    location:"Guarma, New Austin, Flat Iron Lake",
    description:"Large tropical lizards, often basking in the sun",
    imagePath:"/images/wildlife/animals/iguana.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "44",
    name: "Loon",
    type: "Prey",
    location:"Flat Iron Lake, Owanjila, Upper Montana River",
    description:"Waterbirds with haunting calls, often diving for fish",
    imagePath:"/images/wildlife/animals/loon.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "45",
    name: "Moose",
    type: "Prey",
    location:"Aurora Basin, Cairn Lake, Strawberry, Wapiti Indian Reservation, Willard's Rest",
    description:"Towering ungulates with massive antlers, found in cold climates",
    imagePath:"/images/wildlife/animals/moose.png",
    hunting_method:"",
    weapon_type:"Long scope rifle",
  },
  {
    id: "46",
    name: "Mule",
    type: "Prey",
    location:"Emerald Ranch",
    description:"Hardy hybrids of horses and donkeys, used for heavy loads",
    imagePath:"/images/wildlife/animals/mule.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "47",
    name: "Muskrat",
    type: "Prey",
    location:"Most waterways",
    description:"Semi-aquatic rodents often seen swimming in calm waters",
    imagePath:"/images/wildlife/animals/muskrat.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "48",
    name: "Opossum",
    type: "Prey",
    location:"South-central regions",
    description:"Nocturnal marsupials that feign death to evade predators",
    imagePath:"/images/wildlife/animals/opossum.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "49",
    name: "Oriole",
    type: "Prey",
    location:"Lone Mule Stead",
    description:"Brightly colored songbirds often perched in trees",
    imagePath:"/images/wildlife/animals/oriole.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "50",
    name: "Owl",
    type: "Prey",
    location:"Aurora Basin",
    description:"Silent nocturnal hunters with large, piercing eyes",
    imagePath:"/images/wildlife/animals/owl.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "51",
    name: "Oxen",
    type: "Prey",
    location:"Braithwaite Manor, Caliga Hall, Emerald Ranch, Guthrie Farm",
    description:"Strong draft animals used for plowing and pulling carts",
    imagePath:"/images/wildlife/animals/oxen.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "52",
    name: "Panther",
    type: "Predator",
    location:"Old Harry Fen, Lagras, Stillwater Creek",
    description:"Stealthy big cats known for their deadly precision",
    imagePath:"/images/wildlife/animals/panther.png",
    hunting_method:"Long distance use predator bait",
    weapon_type:"",
  },
  {
    id: "53",
    name: "Parakeet",
    type: "Prey",
    location:"Bayou Nwa",
    description:"Small, brightly colored tropical birds",
    imagePath:"/images/wildlife/animals/parakeet.png",
    hunting_method:"Small game arrows",
    weapon_type:"",
  },
  {
    id: "54",
    name: "Parrot",
    type: "Prey",
    location:"Guarma",
    description:"Intelligent and colorful birds often mimicking sounds",
    imagePath:"/images/wildlife/animals/parrot.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "55",
    name: "Peccary",
    type: "Prey",
    location:"Cholla Springs, Rio Bravo, Gaptooth Ridge",
    description:"Pig-like animals roaming deserts and forests",
    imagePath:"/images/wildlife/animals/peccary.png",
    hunting_method:"",
    weapon_type:"Repeater",
  },
  {
    id: "56",
    name: "Pelican",
    type: "Prey",
    location:"Eastern shores",
    description:"Large waterbirds with distinctive throat pouches",
    imagePath:"/images/wildlife/animals/pelican.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  },
  {
    id: "57",
    name: "Pheasant",
    type: "Prey",
    location:"Carmody Dell, Valentine",
    description:"Ground-dwelling birds with colorful plumage",
    imagePath:"/images/wildlife/animals/pheasant.png",
    hunting_method:"Small game arrows",
    weapon_type:"Bow",
  },
  {
    id: "58",
    name: "Pig",
    type: "Prey",
    location:"Saint Denis, Guarma",
    description:"Domesticated swine, common on farms",
    imagePath:"/images/wildlife/animals/pig.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "59",
    name: "Pigeon",
    type: "Prey",
    location:"Bard's Crossing, Annesburg, Saint Denis",
    description:"Hardy urban birds, often found in large flocks",
    imagePath:"/images/wildlife/animals/pigeon.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "60",
    name: "Pronghorn",
    type: "Prey",
    location:"West and Southwest",
    description:"Swift ungulates of the plains, known for their speed",
    imagePath:"/images/wildlife/animals/pronghorn.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "61",
    name: "Quail",
    type: "Prey",
    location:"West Elizabeth, New Austin",
    description:"Small, ground-dwelling birds that scurry through grasslands",
    imagePath:"/images/wildlife/animals/quail.png",
    hunting_method:"",
    weapon_type:"",
  },
  {
    id: "62",
    name: "Rabbit",
    type: "Prey",
    location:"Everywhere",
    description:"Quick and nimble herbivores, common throughout the wild",
    imagePath:"/images/wildlife/animals/rabbit.png",
    hunting_method:"Small game arrows",
    weapon_type:"",
  }, 
  {
    id: "63",
    name: "Raccoon",
    type: "Prey",
    location:"Everywhere but Cholla Springs, Rio Bravo, and Gaptooth Ridge",
    description:"Crafty and curious nocturnal scavengers",
    imagePath:"/images/wildlife/animals/racoon.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  },
  {
    id: "64",
    name: "Rat",
    type: "Prey",
    location:"Everywhere, mainly East",
    description:"Small, invasive rodents often found in settlements",
    imagePath:"/images/wildlife/animals/rat.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  }, 
  {
    id: "65",
    name: "Raven",
    type: "Prey",
    location:"Tanner's Reach, Eris Field",
    description:"Large, intelligent black birds often associated with mystery",
    imagePath:"/images/wildlife/animals/raven.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "66",
    name: "Robin",
    type: "Prey",
    location:"Everywhere except Grizzlies West and New Austin",
    description:"Familiar birds with red breasts, often seen hopping on the ground",
    imagePath:"/images/wildlife/animals/robin.png",
    hunting_method:"Small game arrows",
    weapon_type:"Bow",
  }, 
  {
    id: "67",
    name: "Rooster",
    type: "Prey",
    location:"Guarma, select ranches",
    description:"Male chickens known for their loud crowing",
    imagePath:"/images/wildlife/animals/rooster.png",
    hunting_method:"",
    weapon_type:"",
  },  
  {
    id: "68",
    name: "Sheep",
    type: "Prey",
    location:"Valentine, Emerald Ranch, Beecher's Hope",
    description:"Docile, wooly animals grazing in pastures",
    imagePath:"/images/wildlife/animals/sheep.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "69",
    name: "Skunk",
    type: "Prey",
    location:"Everywhere except Cholla Springs",
    description:"Black-and-white mammals with a notorious defensive spray",
    imagePath:"/images/wildlife/animals/skunk.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "70",
    name: "Snake",
    type: "Predator",
    location:"Everywhere",
    description:"Slithering reptiles, some venomous, others harmless",
    imagePath:"/images/wildlife/animals/snake.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "71",
    name: "Songbird",
    type: "Prey",
    location:"Various",
    description:"Small birds with melodious calls, adding life to the wild",
    imagePath:"/images/wildlife/animals/songbird.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "72",
    name: "Sparrow",
    type: "Prey",
    location:"Everywhere except Gaptooth Ridge, Cholla Springs, and Rio Bravo",
    description:"Common, small birds often seen flitting in bushes",
    imagePath:"/images/wildlife/animals/sparrow.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "73",
    name: "Spoonbill",
    type: "Prey",
    location:"Bayou Nwa",
    description:"Wading birds with distinctive flat, spoon-shaped bills",
    imagePath:"/images/wildlife/animals/spoonbill.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  }, 
  {
    id: "74",
    name: "Squirrel",
    type: "Prey",
    location:"Everywhere",
    description:"Agile tree-dwellers known for their bushy tails",
    imagePath:"/images/wildlife/animals/squirrel.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  }, 
  {
    id: "75",
    name: "Toad",
    type: "Prey",
    location:"Most major waterways",
    description:"Warty amphibians often found near water or damp areas",
    imagePath:"/images/wildlife/animals/toad.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "76",
    name: "Turkey",
    type: "Prey",
    location:"Northern and central regions",
    description:"Large birds with iridescent feathers, found in forests and fields",
    imagePath:"/images/wildlife/animals/turkey.png",
    hunting_method:"",
    weapon_type:"Varmint Rifle",
  },
  {
    id: "77",
    name: "Turtle",
    type: "Prey",
    location:"Bayou Nwa, Stillwater Creek, Flat Iron Lake",
    description:"Slow-moving reptiles with hard shells for protection",
    imagePath:"/images/wildlife/animals/turtle.png",
    hunting_method:"",
    weapon_type:"",
  },  
  {
    id: "78",
    name: "Vulture",
    type: "Prey",
    location:"Armadillo",
    description:"Scavenger birds circling high above carcasses",
    imagePath:"/images/wildlife/animals/vulture.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "79",
    name: "Waxwing",
    type: "Prey",
    location:"Benedict Point, Riggs Station",
    description:"Sleek birds with red-tipped wings, often seen in flocks",
    imagePath:"/images/wildlife/animals/waxwing.png",
    hunting_method:"Small game arrows",
    weapon_type:"",
  },  
  {
    id: "80",
    name: "Wolf",
    type: "Predator",
    location:"Aurora Basin, Hanging Dog Ranch",
    description:"Fearsome predators that hunt in packs across the wild",
    imagePath:"/images/wildlife/animals/wolf.png",
    hunting_method:"",
    weapon_type:"",
  }, 
  {
    id: "81",
    name: "Woodpecker",
    type: "Prey",
    location:"Everywhere except Cholla Springs, Rio Bravo, Gaptooth Ridge, and Great Plains",
    description:"Birds known for pecking at trees in search of insects",
    imagePath:"/images/wildlife/animals/woodpecker.png",
    hunting_method:"",
    weapon_type:"",
  },   
]